name: gosec
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - name: gosec
        uses: securego/gosec@master
        with:
          args: ./…
